# Ansible inventory – generated by Terraform
# Use this file to run ad-hoc commands from your local workstation

[mq_only]
server1 ansible_host=${server1_ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_key_file}

[mq_ace]
server2 ansible_host=${server2_ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_key_file}
server3 ansible_host=${server3_ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_key_file}

[ansible_control]
ansible ansible_host=${ansible_ip} ansible_user=${ansible_user} ansible_ssh_private_key_file=${ssh_key_file}

[all_mq_servers:children]
mq_only
mq_ace

[platform:children]
all_mq_servers
ansible_control
